import { NextRequest, NextResponse } from 'next/server';
import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
import { PDFRequest, Issue } from '@/lib/types';
import { getSeverityScore, getSeverityCounts } from '@/lib/utils';
import { buildReportPayload, getNextSteps } from '@/lib/report';
import { formatWCAGLink, WCAG_MAP } from '@/lib/wcag';
import { z } from 'zod';

const pdfRequestSchema = z.object({
  url: z.string().url().optional(),
  scan: z.object({
    url: z.string(),
    timestamp: z.string(),
    totalIssues: z.number(),
    issues: z.array(z.object({
      id: z.string().optional(),
      ruleId: z.string().optional(),
      impact: z.enum(['critical', 'serious', 'moderate', 'minor']).optional(),
      description: z.string().optional(),
      help: z.string().optional(),
      message: z.string().optional(),
      wcag: z.string().optional(),
      selector: z.string().optional(),
      nodes: z.array(z.object({
        target: z.array(z.string()).optional()
      })).optional(),
      suggestion: z.object({
        summary: z.string().optional(),
        code: z.string().optional(),
        wcag: z.string().optional()
      }).optional()
    })),
    score: z.number().optional(),
    mode: z.string().optional()
  }).optional(),
  includeAI: z.boolean().optional(),
  tier: z.enum(['free', 'paid']).optional()
});

function generateHTMLReport(scan: any, issues: Issue[], includeAI: boolean = false, tier: 'free' | 'paid' = 'free', suggestionsByIssueId: Record<string, { summary: string; code?: string; wcag?: string }> = {}): string {
  // Build report payload with enhanced data
  const reportPayload = buildReportPayload(scan, suggestionsByIssueId);
  const score = reportPayload.score;
  const severityCounts = reportPayload.severityCounts;
  const categoryCounts = reportPayload.categoryCounts;
  const timestamp = new Date(scan.timestamp).toLocaleString();
  const nextSteps = getNextSteps(categoryCounts);
  
  // Limit issues to prevent oversized reports
  const maxIssues = 100;
  const limitedIssues = issues.slice(0, maxIssues);
  const hasMoreIssues = issues.length > maxIssues;
  
  // Group issues by WCAG SC for detailed section
  const issuesByWCAG: Record<string, Issue[]> = {};
  limitedIssues.forEach(issue => {
    if (issue.wcag) {
      const wcagKey = issue.wcag.split(',')[0].trim();
      if (!issuesByWCAG[wcagKey]) {
        issuesByWCAG[wcagKey] = [];
      }
      issuesByWCAG[wcagKey].push(issue);
    }
  });

  // Get top 5-10 pages with most issues (for now, just the main page)
  const pagesWithIssues = reportPayload.pagesWithIssues.slice(0, 10);

  // Generate table of contents
  const tocItems = [
    { id: 'executive-summary', title: 'Executive Summary' },
    { id: 'severity-overview', title: 'Severity & Category Overview' },
    { id: 'pages-issues', title: 'Pages with Most Issues' },
    { id: 'detailed-issues', title: 'Detailed Issues' },
    { id: 'appendix', title: 'Appendix' }
  ];

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Accessibility Report - ${scan.url}</title>
  <style>
    @page { 
      margin: 25mm; 
      @bottom-center { 
        content: "Generated by ADASnapFix | Page " counter(page) " of " counter(pages) " | Report ID: ${reportPayload.reportId}";
        font-size: 10px;
        color: #6b7280;
      }
    }
    
    body { 
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
      line-height: 1.6; 
      color: #1f2937; 
      margin: 0; 
      padding: 0;
      font-size: 11px;
      background: #ffffff;
    }
    
    .page-break { page-break-before: always; }
    .no-break { page-break-inside: avoid; }
    .issue-break { page-break-inside: avoid; margin-bottom: 20px; }
    
    /* Premium Header */
    .header { 
      background: linear-gradient(135deg, #452175 0%, #832626 100%);
      color: white; 
      padding: 40px 30px;
      text-align: center;
      margin-bottom: 40px;
      border-radius: 0 0 20px 20px;
      box-shadow: 0 10px 25px rgba(0,0,0,0.1);
    }
    .header h1 { 
      margin: 0; 
      font-size: 32px; 
      font-weight: 800; 
      letter-spacing: -0.5px;
      text-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .header .subtitle { 
      margin: 8px 0 0 0; 
      font-size: 16px; 
      opacity: 0.9; 
      font-weight: 500;
    }
    .header .meta { 
      margin: 20px 0 0 0; 
      font-size: 12px; 
      opacity: 0.8;
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      max-width: 600px;
      margin-left: auto;
      margin-right: auto;
    }
    .header .meta-item {
      background: rgba(255,255,255,0.1);
      padding: 8px 12px;
      border-radius: 8px;
      backdrop-filter: blur(10px);
    }
    
    /* Dynamic Score Gauge */
    .score-section {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 30px;
      margin: 30px 0;
    }
    
    .score-gauge { 
      position: relative;
      width: 140px; 
      height: 140px;
    }
    
    .gauge-circle {
      width: 100%;
      height: 100%;
      border-radius: 50%;
      background: conic-gradient(
        ${score >= 80 ? '#10b981' : score >= 60 ? '#f59e0b' : '#ef4444'} 0deg ${score * 3.6}deg,
        #f3f4f6 ${score * 3.6}deg 360deg
      );
      position: relative;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    
    .gauge-circle::before {
      content: '';
      position: absolute;
      top: 8px;
      left: 8px;
      right: 8px;
      bottom: 8px;
      background: white;
      border-radius: 50%;
      box-shadow: inset 0 2px 4px rgba(0,0,0,0.1);
    }
    
    .gauge-text {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      text-align: center;
    }
    
    .gauge-score {
      font-size: 28px;
      font-weight: 800;
      color: #1f2937;
      line-height: 1;
    }
    
    .gauge-label {
      font-size: 12px;
      color: #6b7280;
      margin-top: 4px;
    }
    
    .status-badge { 
      display: inline-block; 
      padding: 8px 16px; 
      border-radius: 25px; 
      font-size: 14px; 
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .status-pass { 
      background: linear-gradient(135deg, #10b981, #059669); 
      color: white;
    }
    .status-fail { 
      background: linear-gradient(135deg, #ef4444, #dc2626); 
      color: white;
    }
    
    /* Content Layout */
    .content { padding: 0 30px; }
    .section { margin-bottom: 40px; }
    .section h2 { 
      color: #1f2937; 
      font-size: 24px; 
      font-weight: 700; 
      border-bottom: 3px solid #e5e7eb; 
      padding-bottom: 12px; 
      margin-bottom: 25px;
      position: relative;
    }
    .section h2::after {
      content: '';
      position: absolute;
      bottom: -3px;
      left: 0;
      width: 60px;
      height: 3px;
      background: linear-gradient(135deg, #667eea, #764ba2);
    }
    .section h3 { 
      color: #374151; 
      font-size: 18px; 
      font-weight: 600; 
      margin: 25px 0 15px 0;
    }
    
    /* Table of Contents */
    .toc { 
      background: linear-gradient(135deg, #f8fafc, #f1f5f9); 
      padding: 25px; 
      border-radius: 12px; 
      margin-bottom: 40px;
      border: 1px solid #e2e8f0;
    }
    .toc h2 { border: none; margin-bottom: 20px; }
    .toc h2::after { display: none; }
    .toc ul { list-style: none; padding: 0; margin: 0; }
    .toc li { margin: 8px 0; }
    .toc a { 
      color: #3b82f6; 
      text-decoration: none; 
      font-weight: 500;
      padding: 8px 12px;
      border-radius: 6px;
      transition: all 0.2s;
      display: block;
    }
    .toc a:hover {
      background: rgba(59, 130, 246, 0.1);
    }
    
    /* Executive Summary Cards */
    .summary-grid { 
      display: grid; 
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); 
      gap: 20px; 
      margin: 25px 0;
    }
    .summary-card { 
      padding: 20px; 
      border-radius: 12px; 
      text-align: center;
      border: 1px solid #e5e7eb;
      background: white;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
      transition: transform 0.2s;
    }
    .summary-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    .summary-card.critical { 
      background: linear-gradient(135deg, #fef2f2, #fee2e2); 
      border-color: #fecaca; 
    }
    .summary-card.serious { 
      background: linear-gradient(135deg, #fffbeb, #fef3c7); 
      border-color: #fed7aa; 
    }
    .summary-card.moderate { 
      background: linear-gradient(135deg, #fefce8, #fde68a); 
      border-color: #fde68a; 
    }
    .summary-card.minor { 
      background: linear-gradient(135deg, #f0f9ff, #e0f2fe); 
      border-color: #bae6fd; 
    }
    .summary-card .count { 
      font-size: 32px; 
      font-weight: 800; 
      margin-bottom: 8px; 
      color: #1f2937;
    }
    .summary-card .label { 
      font-size: 12px; 
      color: #6b7280; 
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    /* Category Table */
    .category-table { 
      width: 100%; 
      border-collapse: collapse; 
      margin: 25px 0;
      font-size: 11px;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    .category-table th, .category-table td { 
      border: 1px solid #e5e7eb; 
      padding: 12px 16px; 
      text-align: left;
    }
    .category-table th { 
      background: linear-gradient(135deg, #f8fafc, #f1f5f9); 
      font-weight: 700;
      color: #374151;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-size: 10px;
    }
    .category-table tr:nth-child(even) {
      background: #f9fafb;
    }
    
    /* Issues Table */
    .issues-table { 
      width: 100%; 
      border-collapse: collapse; 
      margin: 25px 0;
      font-size: 10px;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    .issues-table th, .issues-table td { 
      border: 1px solid #e5e7eb; 
      padding: 10px 12px; 
      text-align: left;
      vertical-align: top;
    }
    .issues-table th { 
      background: linear-gradient(135deg, #f8fafc, #f1f5f9); 
      font-weight: 700;
      color: #374151;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-size: 9px;
    }
    .issues-table tr:nth-child(even) {
      background: #f9fafb;
    }
    
    /* Severity Badges */
    .severity-badge { 
      display: inline-block; 
      padding: 4px 10px; 
      border-radius: 6px; 
      font-size: 9px; 
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .severity-critical { background: linear-gradient(135deg, #fef2f2, #fee2e2); color: #dc2626; border: 1px solid #fecaca; }
    .severity-serious { background: linear-gradient(135deg, #fffbeb, #fef3c7); color: #ea580c; border: 1px solid #fed7aa; }
    .severity-moderate { background: linear-gradient(135deg, #fefce8, #fde68a); color: #d97706; border: 1px solid #fde68a; }
    .severity-minor { background: linear-gradient(135deg, #f0f9ff, #e0f2fe); color: #2563eb; border: 1px solid #bae6fd; }
    
    /* Code Blocks */
    .code-block { 
      background: linear-gradient(135deg, #1f2937, #374151); 
      border: 1px solid #4b5563; 
      border-radius: 8px; 
      padding: 15px; 
      font-family: 'JetBrains Mono', 'Fira Code', 'Courier New', monospace; 
      font-size: 10px; 
      overflow-x: auto;
      margin: 15px 0;
      color: #f9fafb;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    
    /* WCAG Section Styling */
    .wcag-section {
      margin-bottom: 30px;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
      overflow: hidden;
      background: white;
      box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    
    .wcag-header {
      background: linear-gradient(135deg, #f8fafc, #f1f5f9);
      padding: 15px 20px;
      border-bottom: 1px solid #e5e7eb;
    }
    
    .wcag-title {
      font-size: 16px;
      font-weight: 700;
      color: #1f2937;
      margin: 0;
    }
    
    .wcag-description {
      font-size: 12px;
      color: #6b7280;
      margin: 5px 0 0 0;
    }
    
    .wcag-issues {
      padding: 20px;
    }
    
    .issue-item {
      margin-bottom: 20px;
      padding: 15px;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      background: #f9fafb;
    }
    
    .issue-header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 10px;
    }
    
    .issue-description {
      font-size: 11px;
      color: #374151;
      margin-bottom: 10px;
      line-height: 1.5;
    }
    
    .issue-selector {
      font-family: 'JetBrains Mono', 'Fira Code', 'Courier New', monospace;
      font-size: 9px;
      background: #1f2937;
      color: #f9fafb;
      padding: 8px 12px;
      border-radius: 6px;
      margin: 10px 0;
      display: block;
      overflow-x: auto;
    }
    
    .fix-section {
      margin-top: 15px;
      padding: 12px;
      background: linear-gradient(135deg, #f0f9ff, #e0f2fe);
      border: 1px solid #bae6fd;
      border-radius: 6px;
    }
    
    .fix-title {
      font-size: 11px;
      font-weight: 700;
      color: #1e40af;
      margin-bottom: 8px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .fix-content {
      font-size: 10px;
      color: #1e3a8a;
      line-height: 1.4;
    }
    
    /* Alert Box */
    .alert-box {
      background: linear-gradient(135deg, #fef3c7, #fde68a);
      border: 1px solid #f59e0b;
      padding: 20px;
      border-radius: 12px;
      margin: 25px 0;
      box-shadow: 0 4px 12px rgba(245, 158, 11, 0.1);
    }
    
    .alert-title {
      font-size: 14px;
      font-weight: 700;
      color: #92400e;
      margin-bottom: 8px;
    }
    
    .alert-content {
      font-size: 11px;
      color: #78350f;
      line-height: 1.5;
    }
    
    /* Footer */
    .footer { 
      margin-top: 50px; 
      padding-top: 25px; 
      border-top: 2px solid #e5e7eb; 
      font-size: 10px; 
      color: #6b7280; 
      text-align: center;
      background: linear-gradient(135deg, #f8fafc, #f1f5f9);
      padding: 20px;
      border-radius: 12px;
    }
    
    /* Print optimizations */
    @media print {
      .header { box-shadow: none; }
      .summary-card:hover { transform: none; }
      .toc a:hover { background: none; }
    }
  </style>
</head>
<body>
  <!-- Header -->
  <div class="header">
    <h1>ADA SnapFix Accessibility Report</h1>
    <p class="subtitle">Professional Accessibility Audit & Compliance Assessment</p>
    
    <div class="score-section">
      <div class="score-gauge">
        <div class="gauge-circle"></div>
        <div class="gauge-text">
          <div class="gauge-score">${score}</div>
          <div class="gauge-label">Score</div>
        </div>
      </div>
      
      <div class="status-badge ${score >= 80 ? 'status-pass' : 'status-fail'}">
        ${score >= 80 ? 'PASS' : 'FAIL'}
      </div>
    </div>
    
    <div class="meta">
      <div class="meta-item">
        <strong>URL:</strong> ${scan.url}
      </div>
      <div class="meta-item">
        <strong>Scanned:</strong> ${timestamp}
      </div>
      <div class="meta-item">
        <strong>Mode:</strong> ${scan.mode || 'standard'}
      </div>
      <div class="meta-item">
        <strong>Report ID:</strong> ${reportPayload.reportId}
      </div>
    </div>
  </div>

  <div class="content">
    <!-- Table of Contents -->
    <div class="section toc">
      <h2>Table of Contents</h2>
      <ul>
        ${tocItems.map(item => `<li><a href="#${item.id}">${item.title}</a></li>`).join('')}
      </ul>
    </div>

    <!-- Executive Summary -->
    <div id="executive-summary" class="section">
      <h2>Executive Summary</h2>
      
      <p><strong>Overall Assessment:</strong> This website ${score >= 80 ? 'meets most accessibility standards' : 'requires significant accessibility improvements'} with a score of ${score}/100.</p>
      
      <div class="summary-grid">
        <div class="summary-card critical">
          <div class="count">${severityCounts.critical}</div>
          <div class="label">Critical Issues</div>
        </div>
        <div class="summary-card serious">
          <div class="count">${severityCounts.serious}</div>
          <div class="label">Serious Issues</div>
        </div>
        <div class="summary-card moderate">
          <div class="count">${severityCounts.moderate}</div>
          <div class="label">Moderate Issues</div>
        </div>
        <div class="summary-card minor">
          <div class="count">${severityCounts.minor}</div>
          <div class="label">Minor Issues</div>
        </div>
      </div>

      <h3>Top 5 Critical Issues</h3>
      <ul>
        ${reportPayload.topIssues.slice(0, 5).map(issue => {
          const wcagInfo = issue.wcag ? WCAG_MAP[issue.wcag.split(',')[0].trim()] : null;
          return `<li><strong>${issue.ruleId || 'Unknown'}</strong>${wcagInfo ? ` (WCAG ${issue.wcag?.split(',')[0].trim()} - ${wcagInfo.title})` : ''}: ${issue.message?.substring(0, 120)}${(issue.message || '').length > 120 ? '...' : ''}</li>`;
        }).join('')}
      </ul>

      <h3>Next Steps</h3>
      <p>${nextSteps}</p>

      <div class="alert-box">
        <div class="alert-title">Legal & User Impact</div>
        <div class="alert-content">
          Accessibility issues can result in legal compliance risks and exclude users with disabilities. 
          Immediate attention to critical and serious issues is recommended to ensure equal access for all users.
        </div>
      </div>
    </div>

    <!-- Severity & Category Overview -->
    <div id="severity-overview" class="section page-break">
      <h2>Severity & Category Overview</h2>
      
      <h3>Issues by Category</h3>
      <table class="category-table">
        <thead>
          <tr>
            <th>Category</th>
            <th>Count</th>
            <th>Percentage</th>
            <th>Priority Level</th>
          </tr>
        </thead>
        <tbody>
          ${Object.entries(categoryCounts).map(([category, count]) => {
            const percentage = Math.round((count / issues.length) * 100);
            const priority = percentage > 30 ? 'High' : percentage > 15 ? 'Medium' : 'Low';
            return `<tr>
              <td><strong>${category}</strong></td>
              <td>${count}</td>
              <td>${percentage}%</td>
              <td>${priority}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>
    </div>

    <!-- Pages with Most Issues -->
    <div id="pages-issues" class="section">
      <h2>Pages with Most Issues</h2>
      <table class="category-table">
        <thead>
          <tr>
            <th>Page URL</th>
            <th>Issue Count</th>
            <th>Severity Breakdown</th>
          </tr>
        </thead>
        <tbody>
          ${pagesWithIssues.map(page => {
            // For now, all issues are from the same page
            const pageSeverityCounts = {
              critical: limitedIssues.filter(i => i.impact === 'critical').length,
              serious: limitedIssues.filter(i => i.impact === 'serious').length,
              moderate: limitedIssues.filter(i => i.impact === 'moderate').length,
              minor: limitedIssues.filter(i => i.impact === 'minor').length
            };
            return `<tr>
              <td><strong>${page.url}</strong></td>
              <td>${page.count}</td>
              <td>C: ${pageSeverityCounts.critical}, S: ${pageSeverityCounts.serious}, M: ${pageSeverityCounts.moderate}, m: ${pageSeverityCounts.minor}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>
    </div>

    <!-- Detailed Issues -->
    <div id="detailed-issues" class="section page-break">
      <h2>Detailed Issues (Grouped by WCAG Success Criteria)</h2>
      ${hasMoreIssues ? `<p><em>Showing first ${maxIssues} issues due to size limits. Full report available in web interface.</em></p>` : ''}
      
      ${Object.entries(issuesByWCAG).map(([wcagId, wcagIssues]) => {
        const wcagInfo = WCAG_MAP[wcagId];
        return `
        <div class="wcag-section issue-break">
          <div class="wcag-header">
            <h3 class="wcag-title">WCAG ${wcagId} - ${wcagInfo?.title || 'Unknown'}</h3>
            <p class="wcag-description">${wcagInfo?.url ? `<a href="${wcagInfo.url}" target="_blank" style="color: #3b82f6;">View WCAG Specification</a>` : ''}</p>
          </div>
          <div class="wcag-issues">
            ${wcagIssues.map(issue => {
              const issueKey = `${issue.ruleId}-${issue.selector}`;
              const suggestion = suggestionsByIssueId[issueKey];
              const priorityScore = reportPayload.issues.find(i => i.ruleId === issue.ruleId && i.selector === issue.selector)?.priorityScore || 0;
              
              return `
              <div class="issue-item">
                <div class="issue-header">
                  <span class="severity-badge severity-${issue.impact || 'moderate'}">${(issue.impact || 'moderate').charAt(0).toUpperCase() + (issue.impact || 'moderate').slice(1)}</span>
                  <strong>Priority Score: ${priorityScore}</strong>
                </div>
                <div class="issue-description">
                  ${issue.message || issue.description || 'No description available'}
                </div>
                <div class="issue-selector">
                  ${issue.selector || 'No selector available'}
                </div>
                ${suggestion ? `
                <div class="fix-section">
                  <div class="fix-title">How to Fix</div>
                  <div class="fix-content">${suggestion.summary}</div>
                  ${tier === 'paid' && suggestion.code ? `
                  <div class="code-block">${suggestion.code}</div>
                  ` : ''}
                </div>
                ` : ''}
              </div>`;
            }).join('')}
          </div>
        </div>`;
      }).join('')}
    </div>

    <!-- Appendix -->
    <div id="appendix" class="section page-break">
      <h2>Appendix</h2>
      
      <h3>WCAG References Used</h3>
      <p>The following WCAG 2.1 Success Criteria were referenced in this report:</p>
      <ul>
        ${Array.from(new Set(issues.map(issue => issue.wcag).filter(Boolean))).map(wcag => {
          const wcagId = wcag?.split(',')[0].trim();
          const wcagInfo = wcagId ? WCAG_MAP[wcagId] : null;
          return `<li><strong>${wcagId}</strong> - ${wcagInfo?.title || 'Unknown'}</li>`;
        }).join('')}
      </ul>

      <h3>Glossary</h3>
      <dl>
        <dt><strong>ARIA (Accessible Rich Internet Applications)</strong></dt>
        <dd>A set of attributes that define ways to make web content more accessible to people with disabilities.</dd>
        
        <dt><strong>Landmarks</strong></dt>
        <dd>HTML elements that identify major sections of a page (header, nav, main, footer, etc.) for screen readers.</dd>
        
        <dt><strong>Contrast Ratio</strong></dt>
        <dd>The ratio of luminance between the brightest and darkest colors in a text/background combination.</dd>
        
        <dt><strong>Focus Indicator</strong></dt>
        <dd>A visual indicator showing which element currently has keyboard focus, essential for keyboard navigation.</dd>
        
        <dt><strong>Semantic HTML</strong></dt>
        <dd>HTML elements that convey meaning about the content they contain, improving accessibility and SEO.</dd>
        
        <dt><strong>Screen Reader</strong></dt>
        <dd>Assistive technology that reads aloud the content of a webpage for users with visual impairments.</dd>
      </dl>
    </div>

    <!-- Footer -->
    <div class="footer">
      <p><strong>Generated by ADA SnapFix Accessibility Scanner</strong></p>
      <p>Report ID: ${reportPayload.reportId} | Generated: ${new Date().toISOString()}</p>
      <p>For detailed fixes and suggestions, visit the web interface.</p>
    </div>
  </div>
</body>
</html>`;

  return html;
}

export async function POST(request: NextRequest) {
  let finalScan: any;
  let issues: Issue[] = [];
  let suggestionsByIssueId: Record<string, { summary: string; code?: string; wcag?: string }> = {};
  
  try {
    const body = await request.json();
    
    // Validate input
    const validation = pdfRequestSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: 'Invalid request format', details: validation.error.issues },
        { status: 400 }
      );
    }

    const { url, scan, includeAI = false, tier = 'free' } = validation.data;

    // If only URL provided, call existing scan API
    if (!scan && url) {
      try {
        const scanResponse = await fetch(`${request.nextUrl.origin}/api/scan`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url })
        });

        if (!scanResponse.ok) {
          return NextResponse.json(
            { error: 'Failed to scan URL', details: 'Scan service unavailable' },
            { status: 503 }
          );
        }

        const scanData = await scanResponse.json();
        finalScan = {
          url: scanData.url,
          timestamp: scanData.timestamp,
          totalIssues: scanData.totalIssues,
          issues: scanData.issues,
          mode: scanData.metadata?.scanType || 'standard'
        };
        issues = scanData.issues;
      } catch (error) {
        return NextResponse.json(
          { error: 'Failed to scan URL', details: 'Internal scan error' },
          { status: 500 }
        );
      }
    } else if (scan) {
      finalScan = scan;
      issues = scan.issues;
    } else {
      return NextResponse.json(
        { error: 'Either url or scan data must be provided' },
        { status: 400 }
      );
    }

    // Get AI suggestions if requested
    if (includeAI && issues.length > 0) {
      try {
        const suggestionsResponse = await fetch(`${request.nextUrl.origin}/api/suggest/batch`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ issues, tier })
        });

        if (suggestionsResponse.ok) {
          const suggestionsData = await suggestionsResponse.json();
          suggestionsByIssueId = suggestionsData.suggestions || {};
        } else {
          console.warn('Failed to get AI suggestions, proceeding without them');
        }
      } catch (error) {
        console.warn('Error getting AI suggestions:', error);
      }
    }

    // Generate HTML report
    const htmlContent = generateHTMLReport(finalScan, issues, includeAI, tier, suggestionsByIssueId);
    
    // Check HTML size limit (increased for larger reports)
    if (htmlContent.length > 200000) {
      return NextResponse.json(
        { error: 'Report too large', details: 'HTML content exceeds size limit for PDF generation' },
        { status: 413 }
      );
    }

    // Launch browser with multiple fallback strategies for Vercel compatibility
    let browser;
    let launchStrategy = 'sparticuz';
    
    try {
      // Strategy 1: @sparticuz/chromium (optimized for Vercel)
      browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: { width: 1280, height: 720 },
        executablePath: await chromium.executablePath(),
        headless: true,
      });
      console.log('PDF browser launched successfully with @sparticuz/chromium');
    } catch (error1) {
      console.log('@sparticuz/chromium failed, trying minimal config...');
      launchStrategy = 'minimal';
      
      try {
        // Strategy 2: Minimal configuration
        browser = await puppeteer.launch({
          headless: true,
          args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-gpu',
            '--disable-web-security',
            '--disable-features=VizDisplayCompositor'
          ]
        });
        console.log('PDF browser launched successfully with minimal config');
      } catch (error2) {
        console.log('Minimal config failed, trying with executable path...');
        launchStrategy = 'executable-path';
        
        try {
          // Strategy 3: With executable path
          browser = await puppeteer.launch({
            headless: true,
            executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH || undefined,
            args: [
              '--no-sandbox',
              '--disable-setuid-sandbox',
              '--disable-dev-shm-usage'
            ]
          });
          console.log('PDF browser launched successfully with executable path');
        } catch (error3) {
          console.error('All PDF browser launch strategies failed, falling back to HTML...');
          
          // Fallback: Return HTML instead of PDF
          console.log('Browser unavailable, returning HTML fallback...');
          const htmlContent = generateHTMLReport(finalScan, issues);
          
          return new NextResponse(htmlContent, {
            status: 200,
            headers: {
              'Content-Type': 'text/html',
              'Content-Disposition': `attachment; filename="ada-snapfix-report-${new Date().toISOString().split('T')[0]}.html"`,
              'Content-Length': htmlContent.length.toString()
            }
          });
        }
      }
    }

    const page = await browser.newPage();
    
    // Set content and wait for rendering
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    // Generate PDF
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm'
      }
    });

    await browser.close();

    // Return PDF with proper headers
    const response = new NextResponse(new Uint8Array(pdf), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="ada-snapfix-report-${new Date().toISOString().split('T')[0]}.pdf"`,
        'Content-Length': pdf.length.toString()
      }
    });
    
    return response;

  } catch (error) {
    console.error('PDF generation error:', error);
    
    // If we get here, it means there was an error after browser launch
    // (like PDF generation or page rendering issues)
    return NextResponse.json(
      { 
        error: 'Failed to generate PDF', 
        details: error instanceof Error ? error.message : 'Internal server error',
        suggestion: 'Try downloading the HTML report instead'
      },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json(
    { message: 'Use POST method with scan data or URL to generate PDF report' },
    { status: 405 }
  );
}
